version: '2'
services:

 jenkins:
  container_name: jenkins
  build: .
  image: accenture/adop-jenkins-dev:0.2.0
  #build: ../images/docker-jenkins/
  expose:
    - "8080"
    - "50000"
  privileged: true
  environment:
    ADOP_GERRIT_ENABLED: "false"
    ADOP_PLATFORM_MANAGEMENT_VERSION: "0.1.1"
    JENKINS_OPTS: "--prefix=/jenkins"
    ROOT_URL: "${PROTO}://${TARGET_HOST}/jenkins/"
    LDAP_SERVER: "${LDAP_SERVER}"
    LDAP_ROOTDN: "${LDAP_FULL_DOMAIN}"
    LDAP_USER_SEARCH_BASE: "${LDAP_USER_BASE_DN}"
    LDAP_USER_SEARCH: "${LDAP_USER_SEARCH}"
    LDAP_GROUP_SEARCH_BASE: "${LDAP_GROUP_BASE_DN}"
    LDAP_GROUP_SEARCH_FILTER: ""
    LDAP_GROUP_MEMBERSHIP_FILTER: ""
    LDAP_MANAGER_DN: "${LDAP_MANAGER_DN}"
    LDAP_MANAGER_PASSWORD: ${LDAP_PWD}
    LDAP_INHIBIT_INFER_ROOTDN: "false"
    LDAP_DISABLE_MAIL_ADDRESS_RESOLVER: "false"
    LDAP_DISPLAY_NAME_ATTRIBUTE_NAME: "displayName"
    LDAP_MAIL_ADDRESS_ATTRIBUTE_NAME: "mail"
    LDAP_GROUP_NAME_ADMIN: "${LDAP_GROUP_NAME_ADMIN}"
    INITIAL_ADMIN_USER: ${INITIAL_ADMIN_USER}
    INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD_PLAIN}
    GERRIT_HOST_NAME: "gerrit"
    GERRIT_FRONT_END_URL: "http://gerrit:8080/gerrit"
    GERRIT_JENKINS_USERNAME: "${GERRIT_JENKINS_USERNAME}"
    GERRIT_JENKINS_PASSWORD: ${PASSWORD_JENKINS}
    BITBUCKET_HOSTNAME: "bitbucket"
    #BITBUCKET_FRONT_END_URL: "http://bitbucket:7990/bitbucket"
    BITBUCKET_ADMIN_USERNAME: "${BITBUCKET_ADMIN_USERNAME}"
    BITBUCKET_ADMIN_PASSWORD: "${BITBUCKET_ADMIN_PASSWORD}"
    BITBUCKET_JENKINS_USERNAME: "${BITBUCKET_JENKINS_USERNAME}"
    BITBUCKET_JENKINS_PASSWORD: ${PASSWORD_JENKINS}
    SONAR_SERVER_URL: "http://sonar:9000/sonar/"
    SONAR_ACCOUNT_LOGIN: ${SONAR_ACCOUNT_LOGIN}
    SONAR_ACCOUNT_PASSWORD: ${PASSWORD_JENKINS}
    SONAR_DB_URL: "jdbc:mysql://sonar-mysql:3306/sonar?useUnicode=true&amp;characterEncoding=utf8"
    SONAR_DB_LOGIN: ${SONAR_DB_LOGIN}
    SONAR_DB_PASSWORD: ${SONAR_DB_PASSWORD}
    SONAR_PLUGIN_VERSION: ""
    SONAR_ADDITIONAL_PROPS: ""
    SONAR_RUNNER_VERSION: "2.4"
    ANT_VERSION: "1.9.4"
    MAVEN_VERSION: "3.0.5"
    NODEJS_VERSION: "0.12.2"
    NODEJS_GLOBAL_PACKAGES: "grunt-cli@~0.1.13 bower@~1.3.12 plato@~1.2.1"
    NODEJS_PACKAGES_REFRESH_HOURS: "72"
    GIT_GLOBAL_CONFIG_NAME: "ADOP Jenkins"
    GIT_GLOBAL_CONFIG_EMAIL: "jenkins@${LDAP_DOMAIN}"
    DOCKER_TLS_VERIFY: ${DOCKER_TLS_VERIFY}
    DOCKER_HOST: ${DOCKER_HOST}
    DOCKER_CLIENT_CERT_PATH: ${DOCKER_CLIENT_CERT_PATH}
    DOCKER_NETWORK_NAME: ${CUSTOM_NETWORK_NAME}
  volumes:
    - jenkins_home:/var/jenkins_home 
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
    driver: local
    
networks:
  default:
    external:
      name: local_network
